library(UpSetR)

set_order = c('Lindley', 'Bedale', 'Luffness', 'Luffness.WGA_N', 'Luffness.WGA_NX', 'Luffness.WGS_NX', 'Newton', 'Pa1', 'Pa1_A.WGA_N', 'Pa1_A.WGA_NX', 'Pa1_A.WGS_NX', 'Pa1_B.WGA_N', 'Pa1_B.WGA_NX', 'Pa1_B.WGS_NX', 'P5A', 'P4A')

expressionInputGenome <- c(`Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 23356067, 
                     `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 2094959, 
                     `Pa1&Pa1_A.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 1627413, 
                     `Pa1&Lindley&Newton&P5A&P4A&Bedale&Luffness` = 1602035, 
                     `Pa1&Pa1_A.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 1425473, 
                     `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 1251472, 
                     `Pa1&Pa1_A.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 992040, 
                     `Pa1&Pa1_A.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 876426, 
                     `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 762282, 
                     `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 697385, 
                     `Pa1&Newton&P5A&P4A&Bedale&Lindley` = 647250)

expressionInputGenes <- c(`Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 15780072, `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 1223909, `Pa1&Pa1_A.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 851281, `Pa1&Pa1_A.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 797793, `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 573783, `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 561434, `Pa1&Pa1_A.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 393709)
expressionInputCDS <- c(`Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 9333374, `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 649647, `Pa1&Pa1_A.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 453330, `Pa1&Pa1_A.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 434140, `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Luffness.WGA_NX&Pa1_B.WGS_NX&Luffness.WGA_N&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 432212, `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Pa1_B.WGA_NX&Bedale&Luffness` = 281166, `Pa1&Pa1_A.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 207841, `Pa1&Pa1_A.WGA_N&Pa1_B.WGA_N&Pa1_B.WGS_NX&Luffness.WGA_N&Lindley&Newton&P5A&P4A&Luffness.WGS_NX&Pa1_A.WGA_NX&Pa1_A.WGS_NX&Bedale&Luffness` = 162815)

upset(fromExpression(expressionInputGenome), order.by = "freq", nsets = 11, sets=set_order,  text.scale = 1, sets.x.label = "Number of bases", mainbar.y.label = "Bases", mb.ratio = c(0.3, 0.7), group.by = "degree", keep.order = TRUE)
upset(fromExpression(expressionInputGenes), order.by = "freq", nsets = 11, sets=set_order,  text.scale = 1, sets.x.label = "Number of bases", mainbar.y.label = "Bases", mb.ratio = c(0.3, 0.7), group.by = "degree", keep.order = TRUE)
upset(fromExpression(expressionInputCDS), order.by = "freq", nsets = 11, sets=set_order,  text.scale = 1, sets.x.label = "Number of bases", mainbar.y.label = "Bases", mb.ratio = c(0.3, 0.7), group.by = "degree", keep.order = TRUE)
5.89*10^-4
# no WGA
set_order = c('Lindley', 'Bedale', 'Luffness', 'Newton', 'Pa1', 'P5A', 'P4A')
expressionInputGenomeNoWGA <- c(`Pa1&Lindley&Newton&P5A&P4A&Bedale&Luffness` = 50187985, `Pa1&Lindley&Newton&P4A&Bedale&Luffness` = 4288955, `Pa1&Newton&P5A&P4A&Bedale&Luffness` = 2877886, `Pa1&Newton&P5A&P4A&Bedale&Lindley` = 1795695, `Bedale&Newton&Lindley&Pa1` = 763227, `Lindley&Newton&P5A&P4A&Bedale&Luffness` = 645040, `Bedale&Newton&Luffness&P4A&Pa1` = 536081, `Luffness&Bedale&Newton&Lindley&Pa1` = 513362, `Bedale&Newton&Luffness&P5A&P4A` = 493212, `Bedale&Newton&Lindley&P5A&Pa1` = 405085, `Bedale&Newton&Lindley&P4A&Pa1` = 398067)
upset(fromExpression(expressionInputGenomeNoWGA), order.by = "freq", nsets = 7 , sets=set_order,  text.scale = 1, sets.x.label = "Number of bases", mainbar.y.label = "Bases", mb.ratio = c(0.3, 0.7), group.by = "degree", keep.order = TRUE)

expressionInputGeneNoWGA <- c(`Pa1&Lindley&Newton&P5A&P4A&Bedale&Luffness` = 25250770, `Pa1&Newton&P5A&P4A&Bedale&Luffness` = 1311099, `Pa1&Lindley&Newton&P4A&Bedale&Luffness` = 709458, `Pa1&Newton&P5A&P4A&Bedale&Lindley` = 407024, `Lindley&Newton&P5A&P4A&Bedale&Luffness` = 132547, `Bedale&Newton&Lindley&Pa1` = 102801, `Bedale&Newton&Luffness&P4A&Pa1` = 90610)
upset(fromExpression(expressionInputGeneNoWGA), order.by = "freq", nsets = 7 , sets=set_order,  text.scale = 1, sets.x.label = "Number of bases", mainbar.y.label = "Bases", mb.ratio = c(0.3, 0.7), group.by = "degree", keep.order = TRUE)

expressionInputCDSNoWGA <- c(`Pa1&Lindley&Newton&P5A&P4A&Bedale&Luffness` = 13726433, `Pa1&Newton&P5A&P4A&Bedale&Luffness` = 875030, `Pa1&Lindley&Newton&P4A&Bedale&Luffness` = 175503, `Pa1&Newton&P5A&P4A&Bedale&Lindley` = 138851, `Lindley&Newton&P5A&P4A&Bedale&Luffness` = 50370, `Bedale&Newton&Luffness&P5A&P4A` = 43520, `Bedale&Newton&Luffness&P4A&Pa1` = 34089, `Bedale&Newton&P5A&P4A&Pa1` = 29002)
upset(fromExpression(expressionInputCDSNoWGA), order.by = "freq", nsets = 7 , sets=set_order,  text.scale = 1, sets.x.label = "Number of bases", mainbar.y.label = "Bases", mb.ratio = c(0.3, 0.7), group.by = "degree", keep.order = TRUE)